const icons = {
  app_dev: require('./Sources/app_dev.png'),
  app_test: require('./Sources/app_test.png'),
  app_prod: require('./Sources/app_prod.png'),
  send: require('./Sources/send.png'),
  back: require('./Sources/arrow-left.png'),
  bullet: require('./Sources/bullet.png'),
  close: require('./Sources/ic_close.png'),
  plus: require('./Sources/ic_plus.png'),
  home: require('./Sources/ic_home.png'),
  heart: require('./Sources/ic_heart.png'),
  search: require('./Sources/ic_search.png'),
  user: require('./Sources/ic_user.png'),
  arrow_down: require('./Sources/arrow_down.png'),
  check: require('./Sources/check.png'),
  swop: require('./Sources/ic_swop.png'),
  wardrobe: require('./Sources/ic_wardrobe.png'),
  profile: require('./Sources/ic_profile.png'),
  filter: require('./Sources/ic_filter.png'),
  deny_user: require('./Sources/ic_deny_user.png'),
  broken_heart: require('./Sources/ic_broken_heart.png'),
  toast_error: require('./Sources/toast_error.png'),
  toast_info: require('./Sources/toast_info.png'),
  toast_success: require('./Sources/toast_success.png'),
  close_large: require('./Sources/ic_close_large.png'),
  maybe: require('./Sources/ic_maybe.png'),
  attach: require('./Sources/ic_attach.png'),
  location: require('./Sources/ic_location.png'),
  map: require('./Sources/ic_map.png'),
  chevron_left: require('./Sources/ic_chevron_left.png'),
  meet_in_person: require('./Sources/ic_meet_in_person.png'),
  laundry_pick_drop: require('./Sources/ic_laundry_pick_drop.png'),
  home_delivery: require('./Sources/ic_home_delivery.png'),
  chat: require('./Sources/ic_chat.png'),
  settings: require('./Sources/settings.png'),
  shipper: require('./Sources/shipper.png'),
  laundry: require('./Sources/ic_laundry.png'),
  earning: require('./Sources/ic_earning.png'),
  warning: require('./Sources/ic_warning.png'),
  oneSize: require('./Sources/ic_one_size.png'),
};

export type IconTypes = keyof typeof icons;

export default icons;
